PREFIX rss: <http://purl.org/rss/1.0/> 
PREFIX dcterms:<http://purl.org/dc/terms/>
PREFIX foaf:<http://xmlns.com/foaf/0.1/>
PREFIX schema:<http://schema.org/>
PREFIX nm: <http://purl.org/stuff/newsmonitor/>

SELECT DISTINCT ?feedTitle ?feedHtml ?feedAuthor ?entry ?title ?content ?updated ?author WHERE { 

GRAPH ?g {
   ?entry a schema:article .
      OPTIONAL { ?source dcterms:title ?feedTitle . }
      OPTIONAL { ?source nm:htmlUrl ?feedHtml . }
      OPTIONAL { ?source dcterms:creator [foaf:name ?feedAuthor] . }
      
      OPTIONAL { ?entry dcterms:source ?source . }
   #   OPTIONAL { ?entry nm:sourceFeed ?feed . }
      OPTIONAL { ?entry dcterms:title ?title . }
      OPTIONAL { ?entry dcterms:updated ?updated . }
      OPTIONAL { ?entry schema:articleBody ?content . }
      OPTIONAL { ?entry dcterms:creator [foaf:name ?author] . }
   }
}
ORDER BY DESC(?updated)