PREFIX rss: <http://purl.org/rss/1.0/> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX schema: <http://schema.org/> 
PREFIX nm: <http://purl.org/stuff/newsmonitor/> 

# DROP <https://www.analyticsvidhya.com/comments/feed/>
# <https://www.analyticsvidhya.com/web-stories/feed/>
# DROP GRAPH <https://ofemwire.com/feed/>
# <https://github.com/ChristosChristofidis/awesome-deep-learning/commits/master.atom>

SELECT DISTINCT *
WHERE { 

GRAPH ?g { 
   ?entry a schema:article . 
      OPTIONAL { ?feedUrl dcterms:title ?feedTitle . }
      OPTIONAL { ?entry dcterms:source ?feedUrl . } 
      OPTIONAL { ?source nm:htmlUrl ?feedHtml . }
      OPTIONAL {    ?entry dcterms:source ?feedUrl . }
      
      OPTIONAL { ?entry dcterms:title ?title . } 
      OPTIONAL { ?entry dcterms:date ?date . } 
      OPTIONAL { ?entry schema:articleBody ?content . } 
      OPTIONAL { ?entry dcterms:creator [foaf:name ?author] . } 
      OPTIONAL { ?entry dcterms:creator [foaf:homepage ?authorHomepage] . } 
      # admin 
      OPTIONAL { ?entry nm:relevance ?relevance . } 
      OPTIONAL { ?entry nm:favourite ?favourite . } 
      OPTIONAL { ?entry nm:read ?read . } 
   }
} 
ORDER BY DESC(?date) 
LIMIT 20 
OFFSET 0 